version: "3"

services:
  web:
    container_name: ui-compare
    image: "bikebook/ui-compare:latest"
    build:
      context: .
      dockerfile: ./apps/ui-compare/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  # api:
  #   container_name: api
  #   build:
  #     context: .
  #     dockerfile: ./apps/api/Dockerfile
  #   restart: always
  #   ports:
  #     - 3001:3001
  #   networks:
  #     - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
